# Generated by Django 3.1.3 on 2020-11-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detail_info', models.CharField(default='', max_length=150, null=True)),
                ('type_code', models.SmallIntegerField()),
                ('is_next_to', models.SmallIntegerField()),
            ],
        ),
    ]
